import React, { useState } from 'react';
import { Modal, Button } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
 
function About() {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <div className="menu-item" onClick={handleShow}>
        <i className="bi bi-person-badge"></i>
        <p>About Us</p>
      </div>

      <Modal show={show} onHide={handleClose}>
        <Modal.Header closeButton className='closeButton'>
          <Modal.Title>Company Introduction</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p>
          Dear Adventurer, <br/>
COSTSAVER was born in 1979 with a simple dream to do good in the world by connecting people to nature. 
 Peter was 21, naïve about business, and filled with a heartfelt passion for sharing wild rivers. 
 Two years later Betsy Bowen joined COSTSAVER as a guide, and we soon became partners in life and business.
  Her wisdom, hard work and energy have been a large part of our success.
   Working with us is an entire team of people that are passionate about travel and curating authentic, meaningful travel experiences for others.
    The best of our collective ideas has been distilled to form what our company is today.
The reality of 40 years comes into focus as we see a second generation of guides and staff – our own children and the children of other COSTSAVER team members – blossom and inspire. 
What joy! We are also inspired that a second, and even third generation of guests is traveling with us!
 Few things are more gratifying than knowing that COSTSAVER has become part of the tradition that lives on in other families.
          </p>
          <p>
            Agents earn 50% of the rewards generated by their subordinates.
          </p>
          Family is a significant word for us. Our own children were shaped by the larger COSTSAVER family. 
          Those who have been part of the COSTSAVER team, are loved as family members. We remain family-owned and operated, independent and, with no one to answer to except you. 
We ask ourselves, as Spokane artist Harold Balazs suggested, “How do I conduct my life so that my efforts end up on the credit column of the planet’s ledgers?” 
This question has guided us and shaped our values.
We are thankful to share with you the celebration of our 40th year! More than ever,
 we believe that travel can be a positive force for good as a bridge between cultures that teaches us that we have much more in common with our global neighbors than differences. 
Walls between us have no place, and only through cooperation and sharing will we meet the challenges of the future.
We hope you find inspiration in these pages to join us. 
We look forward, as always, to sharing with you the warmth of our campfire and our hearts.
          <p><strong> Faithfully yours,</strong></p>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose} className='close-btn' >
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
}

export default About;
