import React, { useState } from 'react';
import { Modal, Button } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import './Agent.css'

function Agent() {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <div className="menu-item" onClick={handleShow}>
        <i className="bi bi-person-badge"></i>
        <p>Agent</p>
      </div>

      <Modal show={show} onHide={handleClose}>
        <Modal.Header closeButton className='closeButton'>
          <Modal.Title>Agent Information</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p>
            Users of the platform can invite others to become agents using an invitation code. 
            Invited members become your downline, and as their upline, you earn a percentage of their rewards. 
            Any reward earned by the upline is directly credited to their platform account.
          </p>
          <p>
            Agents earn 50% of the rewards generated by their subordinates.
          </p>
          <p><strong>Notes:</strong></p>
          <p>
            All platform agents and their downlines receive specific reward percentages from the platform.
          </p>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose} className='close-btn' >
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
}

export default Agent;
